# This is a basic workflow to help you get started with Actions

name: Developer Deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: 
    - Test
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    
    - name: Setup Dot Net
      uses: actions/setup-dotnet@v1
    - run: dotnet restore ./APINewmanTest.sln

    - run: dotnet build ./TestApi/TestApi.csproj --configuration Development --no-restore
    
    - run: dotnet run --project ./TestApi/TestApi.csproj --configuration Development --no-restore
    
    - name: set up node
      uses: actions/setup-node@v1
    
    - name: Install newman
      run: | 
       npm install -g newman
       npm install -g newman-reporter-htmlextra
    
    - name: Make Directory for results
      run: mkdir -p testResults
    
    - name: Run API Tests
      id: run-newman
      uses: anthonyvscode/newman-action@v1
      with:
        delayRequest : 6000
        collection: newman/newmantest.postman_collection.json
        reporters: cli

    - name: Output summary to console
      run: echo ${{ steps.run-newman.outputs.summary }}
